### ISSUE TITLE
Can't attach the console

### ISSUE THREAD

**Issue by max13fr** [dlord/minecraft-docker#3]
Hello,

I would like to send commands to server (I use ftb_infinity image).
I tried "docker attach ftb_infinity" but I don't have anything displayed. Idem when I send some commands like "help".

Do you have any idea to fix this issue ?

Thanks in advance and for you work :)
Max

**Comment by dlord** [comment]
How did you start your container in the first place? This is working fine for me at the moment.

**Comment by dlord** [comment]
There is an issue with the image at the moment, and I'm trying to get it fixed.

**Comment by dlord** [comment]
Issue fixed. Try pulling the latest image, or the 2.3.5 tag
